import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "@next/font/google";
import "./globals.css";
import HeadingBar from "./components/UI/organisms/heading-bar/HeadingBar";
import ContainerHeader from "./components/UI/organisms/ContainerHeader";
const inter = Inter({ subsets: ["latin"],variable:'--font-inter' });
const josefinSaneFont = Josefin_Sans({
  weight: '700',
  subsets:['latin'],
  variable:'--heading-bar-font'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${josefinSaneFont.variable}`}>
        <ContainerHeader/>
        {children}
      </body>
    </html>
  );
}
